### PR TITLE
Add README

### PR DESCRIPTION
**Pull request by sgreene570**

### CODE REVIEW

**Comment by Miciah** [comment]
Do we have any Prow integration?
/approve
/lgtm

**Comment by sgreene570** [comment]
@miciah @openshift/openshift-team-network-edge-maintainers was recently updated, so I _think_ you should have merge rights on this repo now.

**Comment by Miciah** [comment]
I guess we need an `OWNERS` file to merge using Prow, but I can manually merge PRs, so if you want to open a PR to add an `OWNERS` file, I can merge that.

**Pull request merged**
